- src/spootnik/reporter.clj
Previously function `f` was ignored. 
Now it gets registered as a part of gauge.
> Fix the gauge creation.

- src/spootnik/reporter.clj
There are several situations where we want a registry and no reporters:
- use with the Ring middleware
- use during unittests
Therefore, it is convenient to get a registry even without any reporter.
> reporter: create a new registry even without reporters

- deps.edn
- project.clj
- src/spootnik/reporter.clj
This should allow people investigating failures to find things faster/more
easily.
Also refactored the code a little, reduced duplication and ran "lein fmtclj".
> Log event IDs before sending to Sentry

- test/spootnik/reporter_test.clj
A quick test to ensure we do not mess around with the return value.
We used to in a previous version of the library. This came up while chasing for a totally different bug, but at least we got a test out of it.
> tests: add timer test to ensure we don't modify behavior

- src/spootnik/reporter.clj
- test/spootnik/reporter_test.clj
This PR proposes the extraction of the case statement into a multimethod in order to:
- Simplify `build-metrics-reporters`
- Make the logic pluggable
> Extract build-metrics-reporter from build-metrics-reporters

- project.clj
- src/spootnik/reporter.clj
> :cause class com.codahale.metrics.Timer$Context cannot be cast to class clojure.lang.Named (com.codahale.metrics.Timer$Context and clojure.lang.Named are in unnamed module of loader 'app')
> reporter: stop wants a context

- src/spootnik/reporter.clj
capture! should always like the exception, even if `:dsn` is not
defined in the sentry configuration
> capture!: always log exception

- README.md
- project.clj
- src/spootnik/reporter.clj
- src/spootnik/reporter/impl.clj
- test/spootnik/reporter/impl_test.clj
This commit moves the current reporter code in spootnik.reporter.impl.
In spootnik.reporter a singleton for the reporter and some functions
to initialize/use it are added.
> Make the reporter a singleton

- src/spootnik/reporter.clj
> For parts of your own app, you may wish to only enable direct linking when you build and deploy for production, rather than using it when you developing at the REPL. Or you may need to mark parts of your app with ^:redef if you want to always allow redefinition or ^:dynamic for dynamic vars.
> fix missing redef on reporter

- src/spootnik/reporter/impl.clj
As now Raven may return a deferred value, we need to wrap its call as well. Otherwise, we just mute errors which happened when sending alerts.
> Wrap raven's capure! in d/chain

- src/spootnik/reporter.clj
- test/spootnik/reporter/macros_test.clj
Updates the `with-time!` macro to allow timing deferreds or plain values.
We are already pulling aleph, so no extra dependency was needed for manifold deferred support
> feat: allow timing deferred execution

- test/spootnik/reporter/specs_test.clj
The previous DSN wasn't real; but this will prevent people from trying to use it anyway.
CC @aarongroom
> Use a simpler dsn

- project.clj
Java11 removed javax APIs. The riemann TLS driver relies on these to
load certificates.
An explicit dependency needs to be added that provides/backports these
APIs. See https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist
I have tested this on java8 as well, and this does not seem to cause any
issues there.
> fix(deps): Explicitly add javax dependencies for java11

- src/spootnik/reporter/impl.clj
Whether or not the `stop` method actually ends up doing anything, it should always return the component in a stopped state. Without this change, it only does so in the case that `started?` is falsey. When it actually closes connections etc, it ends up returning nil. It seems we have several examples of the reporter not being able to shut down cleanly. Not sure if this is the cause but it should probably be fixed anyway.
> stop method should always return the stopped component

- src/spootnik/reporter/impl.clj
The `job` needs to match what is passed to the impl, although the config requires a keyword, the impl requires a string.
- https://github.com/exoscale/reporter/blob/master/src/spootnik/reporter/specs.clj#L39 (keyword)
- https://github.com/exoscale/reporter/blob/master/src/spootnik/reporter/impl.clj#L339 (string)
>   pushgateway: ensure job is a string

- project.clj
- src/spootnik/reporter/impl.clj
- src/spootnik/reporter/specs.clj
- test/spootnik/reporter/specs_test.clj
The authority key in `tls` section must match what the ssl context factory function expects (eg: `ca-cert`), otherwise the ssl context will be built with a nil CA and SSL host validation will fail.
> pushgateway: fix authority CA key

- src/spootnik/reporter.clj
This PR fixes the `report-error` helper function. There are two changes:
1. The function might take either one or two arguments (in my case, I don't have data to submit).
2. Before, the ordinary `try/catch` form didn't take into account that the `capture!` function returns a deferred value. It means, if there was an HTTP error with Sentry, we'll get the deferred value, so the outer try/catch form would not work. We have already had such issue in Obwald. We `capture!` the message and then terminated the program without dereferencing nor sleeping. That's why we didn't see the messages in Kibana.
> d/chain for capture! function

- src/spootnik/reporter/impl.clj
We are experiencing a Jackson serialization error while trying to capture an error into Sentry
This error is generated before the `manifold.deferred` representing the HTTP call is created
=> we are now wrapping the `raven/capture!` with a try/catch to log when such an error occurs
> sentry: log exception occuring before manifold.deferred is created

- src/spootnik/reporter.clj
- src/spootnik/reporter/impl.clj
- src/spootnik/reporter/specs.clj
Adds support for bundles in client tls configurations through the use of the `:authorities` key.
The configuration has been kept backwards compatible.
> feat(tls): Support ca-bundles in client tls configurations

- README.md
- deps.edn
- project.clj
- src/spootnik/reporter.clj
- src/spootnik/reporter/impl.clj
- src/spootnik/reporter/sentry.clj
- test/spootnik/reporter/impl_test.clj
- Migration to sentry-clj library.
- Getting rid of unsupported raven library.
> Migrate to sentry-clj. Getting rid of raven lib.

- README.md
- src/spootnik/reporter/impl.clj
- src/spootnik/reporter/sentry.clj
The java sdk seems to set `isEnableExternalConfiguration` by default (reading from env vars), or at the very least allows setting that option, while the clj sdk does not. The sentry-clj library is initiated without this option; it's also not possible to set it to `true`, hence we need a way to forwared some options to the sentry library.
This PR forwards the `tags`; `environment` and `release` could already be passed down
https://docs.sentry.io/platforms/java/configuration/#configuration-methods
https://github.com/getsentry/sentry-clj/?tab=readme-ov-file#additional-initialisation-options
> sentry: allow passing base tags

- deps.edn
- project.clj
- src/spootnik/reporter/sentry.clj
- Allow configuring `enable-external-configuration`, which is set to `true` by default
> bump sentry-clj to allow passing :enable-external-configuration

- src/spootnik/reporter.clj
- test/spootnik/reporter/reporter_test.clj
It seems that since [this change](https://github.com/exoscale/reporter/commit/c3fa4f4c6e9273a899a723dd74efa87c3a7768e5#diff-1d086718b79e44223815f06018dd5b132dbd6a516a4437241c8a76a3aedcd7dcL83-R85) we lost the ability to provide a message plus some extra data. Allowed the fn to accept the `:extra` params along the hash map with the `:message` field.
> reporter/report-error: allow reporting a message with extra data

- src/spootnik/reporter/specs.clj
This will make the configs easier to write, currently if we validate the spec, we have to place the `#profile` on the entire block and we can't put it just on the `:tls` key
> spec: spootnik.reporter.config/tls should be nilable

- .github/workflows/default.yml
- README.md
- src/spootnik/reporter/impl.clj
- test/spootnik/reporter/impl_test.clj
Rationale is that if we are somehow measuring elapsed time, we don't want to pollute our timings with pushgateway push
```
(let [start (System/currentTimeMillis)]
(reporter/gauge! {:some "other metric"}) ;; we dont want the elapsed time to include this metrics push
...
(reporter/gauge! {:some "metric} (- (System/currentTimeMillis) start)))
```
This would become:
```
(let [start (System/currentTimeMillis)]
(try
(reporter/gauge! {:some "other metric" :push? false})
...
(reporter/gauge! {:some "metric :push? false} (- (System/currentTimeMillis) start)
(finally 
(reporter/push-metrics!)))
```
> feat(pushgateway): allow pushing at a later time
